global:
  scrape_interval:     15s 
  evaluation_interval: 15s 

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'locationreporter-api'
    static_configs:
      - targets: ['locationreporter-api']

  - job_name: 'monitor-ui'
    static_configs:
      - targets: ['monitor-ui']
  
  - job_name: 'teamservice-api'
    static_configs:
      - targets: ['teamservice-api']

  - job_name: 'proximitymonitor'
    static_configs:
      - targets: ['proximitymonitor']